# Generated by Django 4.0.5 on 2022-11-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animestore', '0002_alter_category_options_alter_imageproduct_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Product Descr', help_text='Product Description', max_length=500),
        ),
    ]
