# Generated by Django 4.0.5 on 2022-11-30 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animestore', '0004_status_alter_product_description_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='status',
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
